### ISSUE TITLE
Complete the building of our improvement feedback loop

### ISSUE THREAD

**Issue by fgregg** [datamade/usaddress#12]
To build a really great parser we need to set up a feedback loop for ourselves.

The loop will include 
1. Testing the performance of the parser on addresses
2. Identifying the failures
3. Altering the parser by
   1. Changing the training corpus by
      1. changing the amount of training data
      2. changing the variety of training data
      3. changing the representativeness of the tranining data
   2. changing the features we use for the model
   3. changing the model form

After making adjustments to the parser (3), we need to be able to evaluate (1) the performance, and identify current difficult cases (2) with one command. 

In the next round, adjustments to the parser (3), need to be based upon our current failures.
- [x] Testing (1 & 2)
  - [x] Start our test corpus: #8 
- [x] Automated build and test #7 
- [x] Patterns for ingesting new training/test data
  - [x] #6 Deciding on data format
  - [x] Directory structure for raw_data, data_scripts, training_data
